### ISSUE TITLE
testcase select03 encountered segmentation fault

### ISSUE THREAD

**Issue by YeechouTang** [linux-test-project/ltp#1185]
Hi,

We encountered a segmentation fault while executing the select03 test case. 

`./runltp -f syscalls -s select03`
...
```
Summary:
passed   24
failed   0
broken   0
skipped  16
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=1 cstime=0
<<<test_end>>>
INFO: ltp-pan reported all tests PASS
LTP Version: 20240524-130-g2d24a286f
```

It seems that the test case ran successfully. However, I found a crash file in the /var/crash directory.

Below is the output from the `bt` command in gdb.

```
Core was generated by `select03'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007faa406a5bc8 in select () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007faa406a5bc8 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055b9a8e66e48 in do_select_faulty_to (faulty_to=1, timeout=<optimized out>, exceptfds=<optimized out>, writefds=<optimized out>, readfds=<optimized out>, nfds=<optimized out>)
    at /opt/ltp/testcases/kernel/syscalls/select/select_var.h:26
#2  verify_select (n=7) at select03.c:49
#3  run (n=<optimized out>) at select03.c:76
#4  0x000055b9a8e7106d in run_tests () at tst_test.c:1489
#5  testrun () at tst_test.c:1555
#6  fork_testrun () at tst_test.c:1684
#7  0x000055b9a8e7348a in tst_run_tcases (argc=<optimized out>, argv=<optimized out>, self=self@entry=0x55b9a8e97060 <test>) at tst_test.c:1820
#8  0x000055b9a8e66a96 in main (argc=<optimized out>, argv=<optimized out>) at ../../../../include/tst_test.h:655
```

LTP: almost the lastest. HEAD commit: 2d24a286f1e35fe6ad7e1e307b86375658e23bee
glibc: Ubuntu GLIBC 2.39-0ubuntu8.2
distribution: Ubuntu 24.04 LTS
kernel: 5.15.0-162

Could someone help analyze this issue? Thank you.

**Comment by metan-ucw** [comment]
The same here, read the source code before submitting an invalid issue.
